#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $PROJECT_DB_USER;
    CREATE DATABASE $PROJECT_DB;
    GRANT ALL PRIVILEGES ON DATABASE $PROJECT_DB TO $PROJECT_DB_USER;
    ALTER ROLE $PROJECT_DB_USER SUPERUSER;
EOSQL