version: "2"
services:
  obnk:
    env_file:
      - ./envs/local.env
    volumes:
      - ./obnk:/data/obnk
      - ./obnk/static:/data/static
      - ./obnk/media:/data/media
    environment:
      - PYTHONUNBUFFERED=0

  nginx:
    volumes:
      - ./obnk/static:/data/static
      - ./obnk/media:/data/media
    ports:
      - "8000:80"

  postgres:
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./envs/local.env
